services:
  # Main services

  # Nginx service
  nginx:
    # image: nginx:latest
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    restart: unless-stopped

  # MariaDB service
  mariadb:
    # image: mariadb:latest
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: unless-stopped

  wordpress:
    # image: wordpress:latest
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file: .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    restart: unless-stopped

  # Bonus services

  # ...

  
volumes:
  # MariaDB volume
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/db
      o: bind
  
  # Wordpress volume
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  # Main network
  mynetwork:
    driver: bridge
