version: '3.7'

services:

  # Main services
  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    restart: always

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/custom-mariadb.cnf:/etc/mysql/my.cnf
    networks:
      - mynetwork
    restart: always

  wordpress:
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    restart: always
  
  # Bonus services
  redis:
    build: ./requirements/bonus/redis
    networks:
      - mynetwork
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
    networks:
      - mynetwork
    volumes:
      - wordpress_files:/var/www/html
    restart: always

  static-site:
    build: ./requirements/bonus/static-site
    ports:
      - "8080:80"
    networks:
      - mynetwork
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - mynetwork
    restart: always

volumes:
  mariadb_data:
  wordpress_files:

networks:
  mynetwork:
    driver: bridge
