services:
  # Main services

  # Nginx service
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    restart: unless-stopped

  # MariaDB service
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: unless-stopped

  # Wordpress service
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file: .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    restart: unless-stopped

  # Bonus services

  # FTP service
  ftp:
    container_name: ftp
    image: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mynetwork
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    restart: unless-stopped

  # Cadvisor service
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  # Static-site service
  website:
    container_name: website
    image: website
    build:
      context: ./requirements/bonus/static-site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    restart: unless-stopped

  # ...

volumes:
  # MariaDB volume
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/db
      o: bind
  
  # Wordpress volume
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  # Main network
  mynetwork:
    driver: bridge
